routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users','UserController');
 Route::get('users/{id}/edit/','UserController@edit');

 Route::get('/admin_logout', 'Auth\LoginController@logout');


 Route::resource('sample', 'SampleController');

Route::post('sample/update', 'SampleController@update')->name('sample.update');

Route::get('sample/destroy/{id}', 'SampleController@destroy');


 Route::resource('company', 'CompanyController');

Route::post('company/update', 'CompanyController@update')->name('company.update');

Route::get('company/destroy/{id}', 'CompanyController@destroy');

Route::resource('admin', 'AdminController');

Route::post('admin/update', 'AdminController@update')->name('admin.update');

Route::get('admin/destroy/{id}', 'AdminController@destroy');



Route::resource('invoice', 'AdminInvoiceController');

Route::post('invoice/update', 'AdminInvoiceController@update')->name('invoice.update');

Route::get('invoice/destroy/{id}', 'AdminInvoiceController@destroy');

Route::get('invoice/pay/{id}', 'AdminInvoiceController@pay');

// Route::get('pdf', function(){
    
//     $pdf = PDF::loadView('invoice_pdf');
//     return $pdf->download('invoice.pdf');
// });

Route::get('invoice/invoice-pdf/{id}', 'AdminInvoiceController@pdf')->name('admin.invoice_pdf');

Route::get('dashboard', 'AdminController@dashboard')->name('admin.dashboard');

Route::get('destroy_records', 'AdminController@destroyRecords');

app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    //user amount product paid print

    protected $fillable = [
        'name', 'product_name', 'amount', 'user_id','paid'
       ];

    
    public function user(){
       return $this->belongsTo('App\User');
    }
}

resources/views/admin/invoices/index.blade.php
{{-- <html>
 <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Datatables</title>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="{{asset('js/libs.js')}}"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>  
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
 </head>
 <body> --}}

  @extends('layouts.admin')

  @section('content')
  {{-- <div class="container">     --}}
     <br />
     <h3 align="center">Invoice Datatables</h3>
     <br />
     <div align="right">
      <button type="button" name="create_record" id="create_record" class="btn btn-success btn-sm">Create Record</button>
     </div>
     <br />
   <div class="table-responsive">
    <table id="user_table" class="table table-bordered table-striped">
     <thead>
      <tr>
                <th width="17%">Invoice Name</th>
                <th width="18%">Product Name</th>
                <th width="15%">Amount</th>
                <th width="20%">User Name</th>
                <th width="30%">Action</th>
      </tr>
     </thead>
    </table>
   </div>
   <br />
   <br />
  {{-- </div> --}}

  <!-- <input id="chk" type="checkbox"  data-toggle="toggle" data-on="paid" data-off="unpaid" data-onstyle="success" data-offstyle="danger"> -->

  @endsection
 </body>
</html>

@section('footer')
<div id="formModal" class="modal fade" role="dialog">
 <div class="modal-dialog">
  <div class="modal-content">
   <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add New Record</h4>
        </div>
        <div class="modal-body">
         <span id="form_result"></span>
         <form method="post" id="sample_form" class="form-horizontal">
          @csrf
          <div class="form-group">
            <label class="control-label col-md-4" >Invoice Name : </label>
            <div class="col-md-8">
             <input type="text" name="name" id="name" class="form-control" />
            </div>
           </div>
           <div class="form-group">
            <label class="control-label col-md-4">Product Name : </label>
            <div class="col-md-8">
             <input type="text" name="product_name" id="product_name" class="form-control" />
            </div>
           </div>
           <div class="form-group" >
            <label class="control-label col-md-4">Amount : </label>
            <div class="col-md-8">
             <input type="text" name="amount" id="amount" class="form-control" />
            </div>
           </div>
           <div class="form-group">
              <label class="control-label col-md-4">User Name : </label>
              <div class="col-md-8">
                <select name="user_name" id="user_name" class="form-control" >
                  @if($users)
                  @foreach($users as $user)
                  <option value="{{ $user->id }}">{{$user->name}}</option>
                  @endforeach
                  @endif
                </select>
              </div>
           </div>
                <br />
                <div class="form-group" align="center">
                 <input type="hidden" name="action" id="action" value="Add" />
                 <input type="hidden" name="hidden_id" id="hidden_id" />
                 {{-- <input type="hidden" name="hidden_company_id" id="hidden_company_id" /> --}}
                 <input type="submit" name="action_button" id="action_button" class="btn btn-warning" value="Add" />
                </div>
         </form>
        </div>
     </div>
    </div>
</div>

<div id="confirmModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Confirmation</h2>
            </div>
            <div class="modal-body">
                <h4 align="center" style="margin:0;">Are you sure you want to remove this data?</h4>
            </div>
            <div class="modal-footer">
             <button type="button" name="ok_button" id="ok_button" class="btn btn-danger">OK</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div id="payModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Confirmation</h2>
            </div>
            <div class="modal-body">
                <h4 align="center" style="margin:0;">Confirm payment?</h4>
            </div>
            <div class="modal-footer">
             <button type="button" name="ok_button" id="ok_button_pay" class="btn btn-danger">OK</button>
                <button type="button" id="cancel_button_pay" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>



<script>
$(document).ready(function(){
    $("#chk").parent('.toggle'). removeClass('off');
    $("#chk").parent('.toggle'). removeClass('btn-danger');
    $("#chk").parent('.toggle'). addClass('btn-success');

    

 $('#user_table').DataTable({
  processing: true,
  serverSide: true,
  ajax: {
   url: "{{ route('invoice.index') }}",
  },
  "order":[[0, 'asc']],
  columns: [
   {
    data: 'name',
    name: 'i.name', 
    orderable: true
    
   },
   {
    data: 'product_name',
    name: 'i.product_name', orderable: true
   },
   {
    data: 'amount',
    name: 'i.amount'
   },
   {
    data: 'user_name',
    name: 'u.name'
   },
   {
    data: 'action',
    orderable: false
   }
  ],

 });

 $('#create_record').click(function(){
  $('.modal-title').text('Add New Record');
  $('#action_button').val('Add');
  $('#action').val('Add');
  // $('#password_inp').show();
  $('#form_result').html('');

  $('#formModal').modal('show');
 });

 $('#sample_form').on('submit', function(event){
  event.preventDefault();
  var action_url = '';

  // $('#hidden_company_id').val($('#role_name').val());

  if($('#action').val() == 'Add')
  {
   action_url = "{{ route('invoice.store') }}";
  }

  if($('#action').val() == 'Edit')
  {
   action_url = "{{ route('invoice.update') }}";
  }

  $.ajax({
   url: action_url,
   method:"POST",
   data:$(this).serialize(),
   dataType:"json",
   success:function(data)
   {
    var html = '';
    if(data.errors)
    {
     html = '<div class="alert alert-danger">';
     for(var count = 0; count < data.errors.length; count++)
     {
      html += '<p>' + data.errors[count] + '</p>';
     }
     html += '</div>';
    }
    if(data.success)
    {
     html = '<div class="alert alert-success">' + data.success + '</div>';
     $('#sample_form')[0].reset();
     $('#user_table').DataTable().ajax.reload();
    }
    $('#form_result').html(html);
   }
  });
 });

 $(document).on('click', '.edit', function(){
  var id = $(this).attr('id');
  // var company_id = $(this).data('company_id');
  // $('#password_inp').hide();
  $('#form_result').html('');
  $.ajax({
   url :"invoice/"+id+"/edit",
   dataType:"json",
   success:function(data)
   {
    $('#name').val(data.result.name);
    $('#product_name').val(data.result.product_name);
    $('#amount').val(data.result.amount);
    $('#user_name').val(data.result.user_id);
    $('#hidden_id').val(id);

    $('.modal-title').text('Edit Record');
    $('#action_button').val('Edit');
    $('#action').val('Edit');
    $('#formModal').modal('show');
   }
  })
 });

 var user_id;

 $(document).on('click', '.delete', function(){
  user_id = $(this).attr('id');
  $('#confirmModal').modal('show');
  $('#ok_button').text('ok');
 });

 $('#ok_button').click(function(){
  $.ajax({
   url:"invoice/destroy/"+user_id,
   beforeSend:function(){
    $('#ok_button').text('Deleting...');
   },
   success:function(data)
   {
    setTimeout(function(){
     $('#confirmModal').modal('hide');
     $('#user_table').DataTable().ajax.reload();
     alert('Data Deleted');
    }, 200);
   }
  })
 });

var pay;
var elem;
var invoice_id;
var switchElem;

 $(document).on('click', '.switch', function(){
  invoice_id = $(this).find('input').attr('id');
  switchElem = $(this).find('input');
  elem = !$(this).find('input').prop("checked");
  // console.log(elem);
  $('#payModal').modal('show');
  $('#ok_button_pay').text('confirm');
 });

 $('#ok_button_pay').click(function(){

  // console.log(elem);
  pay = elem ? 0 : 1;

  $.ajax({
    url:"invoice/pay/"+invoice_id,
    method: "GET",
    data:{paid : pay},
    success:function(data)
   {
    setTimeout(function(){
      $('#payModal').modal('hide');
    //  $('#user_table').DataTable().ajax.reload();
    }, 200);
   }
   
  });
 });

 $('#cancel_button_pay').click(function(){
  if(elem){
    switchElem.prop("checked", true);

  }else{
    switchElem.prop("checked", false);
  }
 });

//  $(document).on('click', '.print', function(){
//   invoice_id = $(this).attr('id');
//   $.ajax({
//     url:"invoice/invoice-pdf/"+invoice_id,
//     method: "GET",
//     success:function(data)
//    {
    
//    }
   
//   });

//  });


});
</script>

@endsection